Medical Data Center Scene: Fixed missing shader in build
Error: scene wouldn't work in build due to missing Krono's (UnityGLTF) shader. Added to Project Settings > Graphics > Preloaded Shaders